# Generated by Django 3.1 on 2021-06-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='imageUrl',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='startingBid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
